version: '3'

services:
  migration:
    build: .
    command: bash -c "
      python manage.py makemigrations room_service
      && python manage.py makemigrations user_service
      && python manage.py migrate
      "
    volumes:
      - .:/code
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - migration

  